- name: download
  get_url:
    url: https://github.com/firecracker-microvm/firecracker/releases/download/v0.23.1/firecracker-v0.23.1-x86_64
    dest: /usr/bin/firecracker
    checksum: sha256:31d87b9169357479145f16476b4d080d1644bba45e297d945dd078dbec3af00f
    mode: '0755'
