FROM ubuntu:20.04 AS builder

RUN apt-get update -y \
 && apt-get install -y \
    bc \
    bison \
    build-essential \
    ccache \
    flex \
    gcc \
    git \
    kmod \
    libelf-dev \
    libncurses-dev \
    libssl-dev
